export const CREATE_CONTACT = 'CREATE_CONTACT';
export const CREATE_CONTACT_SUCCESS = 'CREATE_CONTACT_SUCCESS';
export const CREATE_CONTACT_ERROR = 'CREATE_CONTACT_ERROR';

export const DELETE_CONTACT = 'DELETE_CONTACT';
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';
export const DELETE_CONTACT_ERROR = 'DELETE_CONTACT_ERROR';

export const INIT_CONTACT = 'INIT_CONTACT';
export const INIT_CONTACT_SUCCESS = 'INIT_CONTACT_SUCCESS';
export const INIT_CONTACT_ERROR = 'INIT_CONTACT_ERROR';

export const EDIT_CONTACT = 'EDIT_CONTACT';
export const EDIT_CONTACT_SUCCESS = 'EDIT_CONTACT_SUCCESS';
export const EDIT_CONTACT_ERROR = 'EDIT_CONTACT_ERROR';

export const SEARCH_CONTACT = 'SEARCH_CONTACT';
export const SEARCH_CONTACT_ERROR = 'SEARCH_CONTACT_ERROR';
